test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -98,25 +98,25 @@ jobs:
       run: |
         docker push 861486687156.dkr.ecr.us-east-2.amazonaws.com/phenology-website:latest
 
-    # Step 5: Deploy to AWS App Runner
-    - name: Resume service if needed
-      run: |
-        
-        status=$(aws apprunner describe-service \
-          --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 \
-          --query 'Service.Status' --output text)
-        
-        if [[ "$status" == "PAUSED" ]]; then
-          echo "Service is paused. Resuming now..."
-          aws apprunner resume-service \
-            --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 || {
-            echo "Service resume failed, skipping this step."
-            exit 0
-          }
-          echo "Service resumed."
-        else
-          echo "Service is already running. No need to resume."
-        fi
+    # # Step 5: Deploy to AWS App Runner
+    # - name: Resume service if needed
+    #   run: |
+    #     
+    #     status=$(aws apprunner describe-service \
+    #       --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 \
+    #       --query 'Service.Status' --output text)
+    #     
+    #     if [[ "$status" == "PAUSED" ]]; then
+    #       echo "Service is paused. Resuming now..."
+    #       aws apprunner resume-service \
+    #         --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 || {
+    #         echo "Service resume failed, skipping this step."
+    #         exit 0
+    #       }
+    #       echo "Service resumed."
+    #     else
+    #       echo "Service is already running. No need to resume."
+    #     fi
 
     - name: Update and deploy service
       run: |
@@ -148,29 +148,29 @@ jobs:
           break
         done
     
-    - name: Pause service
-      run: |
-
-        retries=0
-        max_retries=10
-        
-        while [[ $retries -lt $max_retries ]]
-        do
-          # Check if the service is in OPERATION_IN_PROGRESS state
-          status=$(aws apprunner describe-service --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 --query 'Service.Status' --output text)
-
-          echo "Attempt $((retries + 1)) of $max_retries"
-          if [[ "$status" == "OPERATION_IN_PROGRESS" ]]; then
-            echo "Service is still in operation. Waiting for it to finish..."
-            sleep 60 # Wait for 1 minute before checking again
-            retries=$((retries + 1))
-            continue
-          fi
-        
-          # Proceed with pausing if not in OPERATION_IN_PROGRESS state
-          aws apprunner pause-service \
-          --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 
-        
-          echo "Service paused."
-          break
+    # - name: Pause service
+    #   run: |
+    # 
+    #     retries=0
+    #     max_retries=10
+    #     
+    #     while [[ $retries -lt $max_retries ]]
+    #     do
+    #       # Check if the service is in OPERATION_IN_PROGRESS state
+    #       status=$(aws apprunner describe-service --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 --query 'Service.Status' --output text)
+    # 
+    #       echo "Attempt $((retries + 1)) of $max_retries"
+    #       if [[ "$status" == "OPERATION_IN_PROGRESS" ]]; then
+    #         echo "Service is still in operation. Waiting for it to finish..."
+    #         sleep 60 # Wait for 1 minute before checking again
+    #         retries=$((retries + 1))
+    #         continue
+    #       fi
+    #     
+    #       # Proceed with pausing if not in OPERATION_IN_PROGRESS state
+    #       aws apprunner pause-service \
+    #       --service-arn arn:aws:apprunner:us-east-2:861486687156:service/phenology-website-large/2a9d108f65f949c39b51a4191790b269 
+    #     
+    #       echo "Service paused."
+    #       break
         done
